CREATE USER 'db_oda_na'@'localhost' IDENTIFIED BY '***';

GRANT USAGE ON * . * TO 'db_oda_na'@'localhost' IDENTIFIED BY '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `db_oda_na` ;

GRANT ALL PRIVILEGES ON `db_oda_na` . * TO 'db_oda_na'@'localhost';
